name: Badge Job

on:
  push:
    branches:
      - github_workflow_push_docker

jobs:
  badge_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Awesome Badge
        uses: schneegans/dynamic-badges-action@v1.6.0
        with:
          auth: ${{ secrets.GIST_SECRET }}
          gistID: f1612eac8207539733a64b7a531f31f5
          filename: devops_coverage.json
          label: Hello
          message: World
          color: orange
